[package]
name = "fe"
version = "0.1.6"
authors = ["RustemB <bakirov.com@yandex.ru>"]
edition = "2018"
readme = "README.md"

[profile.release]
panic = 'abort'
lto = true
codegen-units = 1
opt-level = 'z'  # Optimize for size.

[dependencies]
serde = "1.0.114"
serde_json = "1.0.57"
serde_yaml = "0.8.13"
ron = "0.6.0"
clap = "2.33.1"
